/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import crud_Taller.conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;//librerias para cambiar la imagen de icono
import java.awt.Toolkit; //librerias para cambiar la imagen de icono
/**
 *
 * @author jeff_
 */
public class Empleados extends javax.swing.JFrame {

    conexion con1 = new conexion();
    Connection conect;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    int idc;

    public Empleados() {
        initComponents();
        consultar();
        setSize(900, 700);
        setResizable(false);
        setTitle("Empleados");
        setLocationRelativeTo(null);
    }

    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Vistas/logo-Zapato.jpg"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAnadirE = new javax.swing.JButton();
        btnActulE = new javax.swing.JButton();
        btnElimiE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNroC = new javax.swing.JTextField();
        txtNomE = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableEmp = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuNomi = new javax.swing.JMenu();
        MenuPres = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Editar Empleado");

        btnAnadirE.setBackground(new java.awt.Color(51, 51, 51));
        btnAnadirE.setForeground(new java.awt.Color(255, 204, 0));
        btnAnadirE.setText("Añadir");
        btnAnadirE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnadirE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirEActionPerformed(evt);
            }
        });

        btnActulE.setBackground(new java.awt.Color(51, 51, 51));
        btnActulE.setForeground(new java.awt.Color(255, 204, 0));
        btnActulE.setText("Actualizar");
        btnActulE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActulE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActulEActionPerformed(evt);
            }
        });

        btnElimiE.setBackground(new java.awt.Color(51, 51, 51));
        btnElimiE.setForeground(new java.awt.Color(255, 204, 0));
        btnElimiE.setText("Eliminar");
        btnElimiE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnElimiE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimiEActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nro. cedula");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cargo:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre Empleado:");

        txtNroC.setBackground(new java.awt.Color(204, 204, 204));
        txtNroC.setForeground(new java.awt.Color(0, 0, 0));

        txtNomE.setBackground(new java.awt.Color(204, 204, 204));
        txtNomE.setForeground(new java.awt.Color(0, 0, 0));

        txtCargo.setBackground(new java.awt.Color(204, 204, 204));
        txtCargo.setForeground(new java.awt.Color(0, 0, 0));

        TableEmp.setBackground(new java.awt.Color(204, 204, 204));
        TableEmp.setForeground(new java.awt.Color(0, 0, 0));
        TableEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cedula", "nombre", "cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableEmpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableEmp);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(469, 469, 469))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomE, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNroC, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnadirE)
                        .addGap(52, 52, 52)
                        .addComponent(btnElimiE)
                        .addGap(50, 50, 50)
                        .addComponent(btnActulE)
                        .addGap(79, 79, 79)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActulE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnElimiE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnadirE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83))
        );

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        MenuNomi.setForeground(new java.awt.Color(0, 0, 0));
        MenuNomi.setText("Nomina");
        MenuNomi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuNomiMouseClicked(evt);
            }
        });
        MenuNomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNomiActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuNomi);

        MenuPres.setForeground(new java.awt.Color(0, 0, 0));
        MenuPres.setText("Prestamos");
        MenuPres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPresMouseClicked(evt);
            }
        });
        MenuPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPresActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuPres);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuNomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNomiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MenuNomiActionPerformed

    private void MenuPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPresActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MenuPresActionPerformed

    private void MenuNomiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuNomiMouseClicked
        // TODO add your handling code here:
        Nomina vistaNomina = new Nomina();
        vistaNomina.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuNomiMouseClicked

    private void MenuPresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPresMouseClicked
        // TODO add your handling code here:
        PrestamosT vistaPrestamos = new PrestamosT();
        vistaPrestamos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuPresMouseClicked

    private void TableEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableEmpMouseClicked
        // TODO add your handling code here:
        int fila = TableEmp.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No has seleccionado la fila correcta");

        } else {
            idc = Integer.parseInt((String) TableEmp.getValueAt(fila, 0).toString());
            String nom = (String) TableEmp.getValueAt(fila, 1);
            String cargo = (String) TableEmp.getValueAt(fila, 2);

            txtNroC.setText("" + idc);
            txtNomE.setText(nom);
            txtCargo.setText(cargo);
        }
    }//GEN-LAST:event_TableEmpMouseClicked

    private void btnAnadirEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirEActionPerformed

        agregar();
        consultar();
        nuevo();
    }//GEN-LAST:event_btnAnadirEActionPerformed

    private void btnElimiEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimiEActionPerformed
        eliminar();
        consultar();
        nuevo();
    }//GEN-LAST:event_btnElimiEActionPerformed

    private void btnActulEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActulEActionPerformed
        actualizar();
        consultar();
        nuevo();
    }//GEN-LAST:event_btnActulEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    //-------------------------------------------------------------------------------------------------------------------------------     
    void agregar() {
        String id = txtNroC.getText();
        String nom = txtNomE.getText();
        String cargo = txtCargo.getText();

        try {
            if (id.equals("") || nom.equals("") || cargo.equals("")) {
                JOptionPane.showInternalMessageDialog(null, "faltan datos por agregar");
            } else {
                String sql = "Insert into empleados (idEmple,nomEmple,cargo) values ('" + id + "','" + nom + "','" + cargo + "')";
//              INSERT INTO `usuario`(`id`, `nombre`, `apellido`, `edad`) VALUES ('[value-1]','[value-2]','[value-3]','[value-4]')
                conect = con1.getConnection();
                st = conect.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Nuevo Empleado registrado");
                limpiar();
            }
        } catch (Exception e) {
        }
    }

    //-------------------------------------------------------------------------------------------------------------------------------  
    void actualizar() {
        String id = txtNroC.getText();
        String nom = txtNomE.getText();
        String cargo = txtCargo.getText();

        try {
            if (id.equals("") || nom.equals("") || cargo.equals("")) {
                JOptionPane.showInternalMessageDialog(null, "faltan datos por agregar");
                
            } else {
                String sql = "UPDATE empleados SET idEmple = '" + idc + "',nomEmple = '" + nom + "',cargo = '" + cargo + "' WHERE idEmple = " + idc;
////            UPDATE `usuario` SET `id`='[value-1]',`nombre`='[value-2]',`apellido`='[value-3]',`edad`='[value-4]' WHERE 1
                conect = con1.getConnection();
                st = (Statement) conect.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Empleado Actualizado");
                limpiar();
            }
        } catch (Exception e) {
        }
    }

    //------------------------------------------------------------------------------------------------------------------------------- 
    void consultar() {
        String sql = "SELECT * FROM empleados";
        try {
            conect = con1.getConnection();
            st = (Statement) conect.createStatement();
            rs = (ResultSet) st.executeQuery(sql);

            Object[] datos = new Object[3];
            modelo = (DefaultTableModel) TableEmp.getModel();

            while (rs.next()) {
                datos[0] = rs.getInt("idEmple");
                datos[1] = rs.getString("nomEmple");
                datos[2] = rs.getString("cargo");

                modelo.addRow(datos);
            }
        } catch (Exception e) {
        }
    }

    //------------------------------------------------------------------------------------------------------------------------------- 
    void eliminar() {
        int fila = TableEmp.getSelectedRow();

        try {
            if (fila < 0) {
                JOptionPane.showMessageDialog(null, "Empleado no seleccionado");
            } else {
                String sql = "DELETE FROM empleados WHERE idEmple =" + idc;
//              DELETE FROM `usuario` WHERE 0
                conect = con1.getConnection();
                st = (Statement) conect.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Se Eliminó al Empleado de la BD");
                limpiar();
            }

        } catch (Exception e) {

        }
    }

    //-------------------------------------------------------------------------------------------------------------------------------     
    void limpiar() {
        for (int i = 0; i <= TableEmp.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

//-------------------------------------------------------------------------------------------------------------------------------     
    void nuevo() {
        txtNroC.setText("");
        txtNomE.setText("");
        txtCargo.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuNomi;
    private javax.swing.JMenu MenuPres;
    private javax.swing.JTable TableEmp;
    private javax.swing.JButton btnActulE;
    private javax.swing.JButton btnAnadirE;
    private javax.swing.JButton btnElimiE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtNomE;
    private javax.swing.JTextField txtNroC;
    // End of variables declaration//GEN-END:variables
}
